---

- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  # pre_tasks:
  #   - name: "wait 300 seconds for target connection to become reachable/usable."
  #     wait_for:
  #       timeout: 300

    # - name: "install python for Ansible."
    #   # Your code here

  roles:
    - configure-server


  environment:
    ENVIRONMENT: production
    CIRCLE_WORKFLOW_ID: "{{ lookup('env','CIRCLE_WORKFLOW_ID') }}"
    TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}"
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"


  # environment:
  #   - ENVIRONMENT=production
  #   - TYPEORM_CONNECTION=postgres
  #   - TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
  #   - TYPEORM_HOST=udapeople-prod.cwvhgsfozke7.us-east-2.rds.amazonaws.com
  #   - TYPEORM_PORT=5432
  #   - TYPEORM_USERNAME=postgres
  #   - TYPEORM_PASSWORD=udapeople1234
  #   - TYPEORM_DATABASE=udapeople-prod
