  - name: "Creates directory"
    file:
      path: ~/web
      state: directory

  - name: Copy compiled files in dist to backend
    synchronize:
      src: "../../backend/"
      dest: "~/web/"
      recursive: yes

  - name: Executing node
    command: pm2 start -f ./main.js
    args:
      chdir: ~/web/dist
    environment:
      ENVIRONMENT: production
      CIRCLE_WORKFLOW_ID: "{{ lookup('env','CIRCLE_WORKFLOW_ID') }}"
      TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}"
      TYPEORM_MIGRATIONS_DIR: "{{ lookup('env','TYPEORM_MIGRATIONS_DIR') }}"
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
      # # further variables
      # TYPEORM_MIGRATIONS_DIR: "./migrations"
      # TYPEORM_MIGRATIONS: "./migrations/*.js"
      # TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
